---

plugins:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - fluent-plugin-ldap-client.gemspec
    - test/**/*.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 10
  Exclude:
    - test/helper.rb

Metrics/PerceivedComplexity:
  Max: 10

Naming/MethodParameterName:
  Exclude:
    - lib/fluent/plugin/filter_ldap_enrich.rb

Style/Documentation:
  Enabled: false
